#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # colorscheme = "gruvbox"
    # colorscheme = "palenight"
    colorscheme = "molokai"

    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false

    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

    default_indent = 4

    # 添加自己的部分设置
    bootstrap_before = "myspacevim#before"

# 启用颜色主题
[[layers]]
    name = "colorscheme"

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "smart"
    autocomplete_parens = false

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = "lang#markdown"

[[layers]]
    name = "lang#python"
    python_file_head = [
    '#!/usr/bin/env python',
    '# -*- coding: utf-8 -*-',
    '# @Author: Alrash',
    '# @Email: kasukuikawai@gmail.com',
    '',
    ''
    ]
    format_on_save = 1

# #latex
# [[layers]]
#     name = "lang#latex"

# [[custom_plugins]]
#     name = "xuhdev/vim-latex-live-preview"
#     merged = false

[[custom_plugins]]
    name = "vim-latex/vim-latex"
    merged = false
